# Лабораторная работа 6
Цели: Изучить метод Флойда.<br>
Задачи: Реализовать метод Флойда для нахождение кратчайших путей в взвешенном ориентированном графе.

Псевдокод алгоритма<br>
![](1.png)
![](3.png)
![](4.png)


Формула Алгоритма<br>
![](2.png)

![](5.png)

In [13]:
import numpy as np
def floyd_warshall(W,Pi):
    n = W.shape[0]
    D = W
    P = Pi
    for k in range(n):
        D_next = np.zeros(shape = W.shape)
        P_next = np.zeros(shape = W.shape)
        for i in range(n):
            for j in range(n):
                D_next[i,j] = np.min([D[i,j],D[i,k]+D[k,j]])
                if D_next[i,j] == D[i,j]:
                    P_next[i,j] = P[i,j]
                else:
                    P_next[i,j] = P[k,j] 
        D = D_next
        P = P_next
    return (D,P)


In [15]:
W = np.array([[0,3,8,np.inf,-4],
    [np.inf,0,np.inf,1,7],
    [np.inf,4,0,np.inf,np.inf],
    [2,np.inf,-5,0,np.inf],
    [np.inf,np.inf,np.inf,6,0]])
Pi = np.array([[np.NAN,1,1,np.NAN,1],
    [np.NAN,np.NAN,np.NAN,2,2],
    [np.NAN,3,np.NAN,np.NAN,np.NAN],
    [4,np.NAN,4,np.NAN,np.NAN],
    [np.NAN,np.NAN,np.NAN,5,np.NAN]])
D,P = floyd_warshall(W,Pi)
print(D)
print(P)


[[ 0.  1. -3.  2. -4.]
 [ 3.  0. -4.  1. -1.]
 [ 7.  4.  0.  5.  3.]
 [ 2. -1. -5.  0. -2.]
 [ 8.  5.  1.  6.  0.]]
[[nan  3.  4.  5.  1.]
 [ 4. nan  4.  2.  1.]
 [ 4.  3. nan  2.  1.]
 [ 4.  3.  4. nan  1.]
 [ 4.  3.  4.  5. nan]]


![](6.png)

Вывод: В результате работы был реализован алоритм Флойда