# Лабораторная работа 7


![](6.png)
![](7.png)

Псевдокод алгоритма<br>
![](3.png)

![](4.png)
![](5.png)

Примеры<br>
![](1.png)
![](2.png)

In [6]:
# Ford-Fulkerson algorith in Python

from collections import defaultdict


class Graph:

    def __init__(self, graph):
        self.graph = graph
        self. ROW = len(graph)


    # Using BFS as a searching algorithm 
    def searching_algo_BFS(self, s, t, parent):

        visited = [False] * (self.ROW)
        queue = []

        queue.append(s)
        visited[s] = True

        while queue:

            u = queue.pop(0)

            for ind, val in enumerate(self.graph[u]):
                if visited[ind] == False and val > 0:
                    queue.append(ind)
                    visited[ind] = True
                    parent[ind] = u

        return True if visited[t] else False

    # Applying fordfulkerson algorithm
    def ford_fulkerson(self, source, sink):
        parent = [-1] * (self.ROW)
        max_flow = 0

        while self.searching_algo_BFS(source, sink, parent):

            path_flow = float("Inf")
            s = sink
            while(s != source):
                path_flow = min(path_flow, self.graph[parent[s]][s])
                s = parent[s]

            # Adding the path flows
            max_flow += path_flow

            # Updating the residual values of edges
            v = sink
            while(v != source):
                u = parent[v]
                self.graph[u][v] -= path_flow
                self.graph[v][u] += path_flow
                v = parent[v]

        return max_flow,self.graph

import numpy as np

graph = [[0, 8, 0, 0, 3, 0],
         [0, 0, 9, 0, 0, 0],
         [0, 0, 0, 0, 0, 2],
         [0, 0, 0, 0, 0, 5],
         [0, 0, 7, 4, 0, 0],
         [0, 0, 0, 0, 0, 0]]
import copy
graph_copy = copy.deepcopy(graph)
g = Graph(graph)

source = 0
sink = 5

print("Max Flow: %d " % g.ford_fulkerson(source, sink)[0])

print(f"Graph \n :{np.array(graph_copy) - np.array(g.ford_fulkerson(source, sink)[1])}")

Max Flow: 5 
Graph 
 :[[ 0  2  0  0  3  0]
 [-2  0  2  0  0  0]
 [ 0 -2  0  0  0  2]
 [ 0  0  0  0 -3  3]
 [-3  0  0  3  0  0]
 [ 0  0 -2 -3  0  0]]
